### ISSUE TITLE
Annoying logs related to invalid message root

### ISSUE THREAD

**Issue by hackfisher** [darwinia-network/darwinia#1013]
[error-log.txt](https://github.com/darwinia-network/darwinia/files/10947991/error-log.txt)

**Comment by AurevoirXavier** [comment]
This is a warning log; we shouldn't change its level. And there is no way to remove these logs for the existing blocks. If you sync the node from the start, you'll see a lot of logs like this because the log code is stored in the wasm code in the storage.

I think we can disable the log for the release on-chain wasm in the next version.
