### ISSUE TITLE
How can treasury account support/transfer holding ERC20 tokens?

### ISSUE THREAD

**Issue by hackfisher** [darwinia-network/darwinia#1282]

**Comment by boundless-forest** [comment]
I successfully conducted a local testnet test after making some investments. During the test, I deployed a contract using a specific derived account through a government approach. You can see the screenshot below for reference. @hackfisher @AurevoirXavier 

The solution I used involved the Utility -> DispatchAs -> MessageTransact Pallet -> message_transact call. Not only did the contract deployment work, but the call to the ERC20 contract also functioned properly.

![image](https://github.com/darwinia-network/darwinia/assets/11801722/bacab2f6-4990-47e5-9961-a294cacd43c4)

The reason for choosing MessageTransact instead of Ethereum pallet is that the message-transact pallet will automatically fills in some transaction fields, such as gas_price, nonce. This way we can avoid some potential validation failures in the execution phase.

![image](https://github.com/darwinia-network/darwinia/assets/11801722/f3bc8f21-bc80-42f8-b48c-630c53b891d1)

**Comment by AurevoirXavier** [comment]
I suggested using `utility::dispatch_as` initially.

Now, I believe we can develop a new pallet that combines the advantages of both `dispatch_as` and `transact`. Or improve and rename the message-transact pallet to make it more general.

**Comment by boundless-forest** [comment]
> Now, I believe we can develop a new pallet that combines the advantages of both dispatch_as and transact. Or improve and rename the message-transact pallet to make it more general.
I don't think it's necessary to add a new pallet to combine these two functionalities. Composity is better than a dedicated entity in this case. The name "message-transact" comes from combining "message" from the LCMP protocol and "transact" from the Ethereum pallet.  It also makes sense to me~

**Comment by hackfisher** [comment]
> I suggested using `utility::dispatch_as` initially.
> 
> Now, I believe we can develop a new pallet that combines the advantages of both `dispatch_as` and `transact`. Or improve and rename the message-transact pallet to make it more general.

If use `utility::dispatch_as` can we use the following dispatch call as runtime call, what else modification we need to do before making a test?

```
pub fn transact(
			origin: OriginFor<T>,
			transaction: Transaction,
		) -> DispatchResultWithPostInfo {
```

https://github.com/paritytech/frontier/blob/aea528198b3b226e0d20cce878551fd4c0e3d5d0/frame/ethereum/src/lib.rs#L284C19-L287

**Comment by hackfisher** [comment]
Please use these two calls to demonstrate the solution for the title based on current runtime.

**Comment by hackfisher** [comment]
For other improvements for the runtime, we can continue the thread with more research and discussion.

**Comment by hackfisher** [comment]
Another question:

Using super permission root frequently for managing assets like ERC20 will look dangerous and  cost ineffective.

**Comment by boundless-forest** [comment]
mocked Crab chain signature:

```sh
signature: { 
    v: TransactionRecoveryId(124), 
    r: 0x0cb0d711fcdf2770cfa5e094fb3a33c2c7e17e0337eca4d3b7f82808f81272df, 
    s: 0x5faa5047e1337278c25a5625c65b77710a445bee1f4bd9cdf9c3f7c2a0f1469a 
}
```

**Comment by hujw77** [comment]
https://github.com/itering/internal-security-audit/issues/77

**Comment by boundless-forest** [comment]
mocked Pangolin chain signature:
```sh
signature: TransactionSignature { 
    v: TransactionRecoveryId(119), 
    r: 0xb00f64117ca7d3849cfd7688f532123b1cf16c7e11a789a61ca83132e97f17d0, 
    s: 0x02064f241d10d2aa70acb2d7da031d6c0f81cfb850de98b4ed7c447278af3983 
    } 
})
```
