### ISSUE TITLE
Unstaking deposits doesn't require a 14-day wait.

### ISSUE THREAD

**Issue by AurevoirXavier** [darwinia-network/darwinia#1454]
Deposited RING is already locked for at least 1 month.
It's reasonable to unstake it immediately.

In the Darwinia 1, users can redeposit immediately if a deposit is expired.

**Comment by hackfisher** [comment]
> Deposited RING is already locked for at least 1 month.
> It's reasonable to unstake it immediately.

I disagree, RING in deposit is locked for the return of KTON interest, not for staking.

The deposit is a NFT holding the deposit, staking/unstake deposit is just like stake/unstake a NFT token.

**Comment by hackfisher** [comment]
14-day wait is for slash purpose, if the collator staking is not going to support slash anymore, the RING token in staking can remove the wait too, it is not different with deposit NFT.

What is NFT inner status is opache to staking by design.

And the deposit and collator staking will be moved to application level implementation, I would rather give it low priority and discuss in the next version of deposit.

**Comment by hackfisher** [comment]
stake and unstake rate limiting can prevent sudden fluctuation to the collators, which might be better. Rate limit, in a period, only specific amount of staking tokens can be staked/unstaked at most.

**Comment by hackfisher** [comment]
I've given it some thought, and since there's currently no slashing mechanism in collator staking, we could remove the unstaking wait (for RING and deposit). 

1. This would require writing an RFC forum post, followed by a transition to a DIP for easier engineering implementation and future migration to a contract. 
2. At the moment, I don't want to spend too much time changing the protocol within the runtime. If a user stakes and unstakes before and after a session, they wouldn't need to lock up funds but could still interfere with collator election. 
3. We might consider a measure, such as requiring a minimum stake duration of one session before unstaking. 

Considering we haven't fully researched item 3, my current recommendation might still be to avoid any changes.

**Comment by SasoLithops** [comment]
Hi! If I may add the main problem  for community is when our (3 year) locks are expired we all have to unbond each lock and wait 14 days so we can rebond again. In V1 you could use Lock Extra to immediately continue bonding again. 
Would be good if we had that option back.

**Comment by hackfisher** [comment]
> Hi! If I may add the main problem for community is when our (3 year) locks are expired we all have to unbond each lock and wait 14 days so we can rebond again. In V1 you could use Lock Extra to immediately continue bonding again. Would be good if we had that option back.

For simplicity and security, different modules typically implement secure isolation to prevent abnormal calls. For example, the staking module should not be able to handle deposit logic for users, especially in the next design. If such operations are supported now, it would add unnecessary complications to future migration designs.

Ref: https://github.com/darwinia-network/darwinia/issues/1395

**Comment by SasoLithops** [comment]
You were to fast in reply😀I wanted to post some examples:

![IMG_20240326_081849.jpg](https://github.com/darwinia-network/darwinia/assets/101176902/ea66da7e-595c-4226-a3a4-c8f87b2a5133)

![IMG_20240326_081825.jpg](https://github.com/darwinia-network/darwinia/assets/101176902/6a9d2938-d77e-44d7-96cf-a6f300b001d2)

![IMG_20240326_081803.jpg](https://github.com/darwinia-network/darwinia/assets/101176902/c2c118d8-1adb-412e-9554-7fe478351981)

![IMG_20240326_081741.jpg](https://github.com/darwinia-network/darwinia/assets/101176902/dafcad26-be63-46aa-8686-bd6bedd11f8e)

![IMG_20240326_081721.jpg](https://github.com/darwinia-network/darwinia/assets/101176902/274c39f8-7613-4105-ae8f-e0f7a37bcc5d)

**Comment by SasoLithops** [comment]
If you find to not use Lock extra for te hnical reasonsI understand. I have no knowledge there.

**Comment by SasoLithops** [comment]
If you find to not use Lock extra for technical reasons I understand. I have no knowledge there. 
I am trying to be as objective here as I can, as I have also many locks expiring as I bonded weekly/biweekly, but I can take the wait of 14 days.  I think from user perspective this is still very time/rewards consuming.

**Comment by hackfisher** [comment]
Before we reach full consensus, or before we figure out how to completely cancel staking, shall we reduce this period to 7 days or 3 days? Keep it simple and minimal in terms of protocol modification.

**Comment by SasoLithops** [comment]
If it doesn't hurt the network and I guess it doesn't now I am all for simplicity.
I am fine with either options. Although we all know what community would vote on if both options were presented😉

**Comment by hackfisher** [comment]
For the technical research:

https://ethresear.ch/t/rate-limiting-entry-exits-not-withdrawals/4942

**Comment by hackfisher** [comment]
https://github.com/orgs/darwinia-network/discussions/1455

**Comment by SasoLithops** [comment]
Maybe I still don't understand well. Just to be 100% sure we are talking about same thing I was talking about continuation of bonding not exiting staking.

My example is:

Let's say I always lock Ring for 36 months.


So in past I locked Ring for 36 months and it expires today. 

In V2 I have to wait for 14 days to unbond and then I need to withdraw to lock again for 36 months.

In V1 all I needed to do was click on "Lock extra" and I could immediately rebond for 36 months. 
*I still had to wait 14 days to unbond and withdraw, but that is not my intention in example above.


So "Lock extra" was not about withdrawal or unstaking at all, just imediate relocking for another time frame to mint Kton.

**Comment by hackfisher** [comment]
> Maybe I still don't understand well. Just to be 100% sure we are talking about same thing I was talking about continuation of bonding not exiting staking.
> 
> My example is:
> 
> Let's say I always lock Ring for 36 months.
> 
> 
> So in past I locked Ring for 36 months and it expires today. 
> 
> In V2 I have to wait for 14 days to unbond and then I need to withdraw to lock again for 36 months.
> 
> In V1 all I needed to do was click on "Lock extra" and I could immediately rebond for 36 months. 
> *I still had to wait 14 days to unbond and withdraw, but that is not my intention in example above.
> 
> 
> So "Lock extra" was not about withdrawal or unstaking at all, just imediate relocking for another time frame to mint Kton.
> 
> 

Yes, using this RFC can eliminate this issue you mention:

Unstake deposit right way, claim from deposit, deposit as you like, stake again. 4 txs, no wait. 

Why not support those in 1 extrinsic call in collator staking? 

In protocol, currently the collator staking is not designed to operate deposit, better to keep it simple, especially before we are going to re-implement it using smart contract, marking this more like a technical debt instead of being an improvement.
(There is possibility that in the future collator staking contact, a re-deposit call can be introduced to claim from deposit & and burning deposit NFT, re-deposit & minting new NFT, put the NFT under the user's account in collator staking again, But better way should still be using a spectate re-deposit contract to manage this for user if they want this, and keep collator staking contract simple, reducing the security audit burden for the the protocol and core contracts)

**Comment by SasoLithops** [comment]
I understand now. Thank you for your time and patience in explaining. 
Agree. Simple and o need for any potential security issues.

**Comment by hackfisher** [comment]
Ah, you are talking about adding an extra lock period in deposit?

That is some advance feature deposit can have, I understand now, it is not related with collator staking, I am fine with it... though I still give it low priority since the RFC can eliminate this issue you mentioned.



(in the smart contract version of staking, the deposit NFT is hold by the collator staking contract, it still need to do that though staking module.)

**Comment by SasoLithops** [comment]
Yes. Please check the pictures I posted from TG about community members asking about this. Also many of us early stakers have same issue. 
We all have to wait 14 days to unbond then withdraw and bond again. Lock extra would be great if it could be added.
That is why I thought we maybe don't understand each other.
